language: objective-c
xcode_project: Steam IM.xcodeproj
xcode_scheme: Steam IM
before_install:
  - cd polarssl; mkdir build; cd build; cmake -DCMAKE_OSX_ARCHITECTURES="i386;x86_64" ..; make; cd ../..
  - mkdir adium; cd adium; wget https://bitbucket.org/adium/adium/get/adium-1.5.10.tar.gz
  - tar xf adium-1.5.10.tar.gz --strip-components=1;
  - xctool -configuration Release -scheme Adium; cd ..