language: objective-c
before_install:
  - wget https://bitbucket.org/adium/adium/get/adium-1.5.10.tar.gz
  - mkdir adium
  - tar xf adium-1.5.10.tar.gz -C adium/ --strip-components=1
  - cd adium
  - xctool -scheme Adium build
  - cd ..
  - cd polarssl; mkdir build; cd build; cmake -DCMAKE_OSX_ARCHITECTURES="i386;x86_64" ..; make
branches:
  only:
    - travis-ci
