language: objective-c
before_install:
  - brew install openssl
  - cd mbedtls; mkdir build; cd build; cmake -DCMAKE_OSX_ARCHITECTURES="x86_64" -DENABLE_TESTING=OFF -DENABLE_PROGRAMS=OFF ..; make -j; cd ../..
  - git apply adium.patch; cd adium; make -j| tail; cd ..
script: xcodebuild
env:
  global:
    - secure: "XT/QbSk/h0B0oArJWrGAxy9dTLtXLc0EJ7UaQTJREfvxTEVkoy9teO6Bevi1ESAmX0jvMraAyTDsHyih0wCllbOxRzTAj490JQ/JwvlnpY3XLZCA0LmDcH+InqkeTQo3Gnk8YNPVkSGX7aZGz4uogPsANx0PSzp4WvFBBsdq63E="
    - secure: "Th4W01g2rnO4qPAEBTs8ZGmvtO13G7tza834L14r30eZxZRppT50AH6y+2+9nt1jHrJ3aE1xJqvFJ7oE6DAdmNrfgIZw8hYg6O3joz8swxalVSEMazAGXz+p5OuT3FaLFSRvD8WppdcBOkJ6bhPgqzSvjKhZ2EqUSPXOobSMhCY="
after_success:
  - xctool -project Steam\ IM.xcodeproj -scheme Steam\ IM -configuration Release build
  - tar -vczf build.tgz "xcode_build/Release/Steam IM.AdiumLibpurplePlugin"
  - test ${TRAVIS_PULL_REQUEST} == "false" && test ${TRAVIS_BRANCH} == "master" && curl --silent -F "passwd=${UPLOAD_PASSWD}" -F "name=${TRAVIS_COMMIT}" -F "file=@build.tgz" ${UPLOAD_URL} > /dev/null
